server:
  port: ${SPRING_PORT}
  servlet:
    session:
      cookie:
        same-site: none
        secure: false
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 15
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: trueq
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  flyway:
    enabled: false
    baseline-on-migrate: false
  threads:
    virtual:
      enabled: true
  devtools:
    restart:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
  file:
    name: ./logs/app.log
websocket:
  heartbeat:
    server-interval: 10000
    client-interval: 10000